export interface Product {
  id: string
  name: string
  price: number
  category: string
}

export interface Category {
  id: string
  name: string
  emoji: string
  products: Product[]
}

export const categories: Category[] = [
  {
    id: "viennoiseries",
    name: "Viennoiseries & Patisseries",
    emoji: "🥐",
    products: [
      { id: "croissant-beurre", name: "Croissant au beurre", price: 1.10, category: "viennoiseries" },
      { id: "pain-chocolat", name: "Pain au chocolat", price: 1.20, category: "viennoiseries" },
      { id: "pain-lait", name: "Pain au lait", price: 1.20, category: "viennoiseries" },
      { id: "brioche-tete", name: "Brioche a tete", price: 1.20, category: "viennoiseries" },
      { id: "pain-raisins", name: "Pain aux raisins", price: 1.40, category: "viennoiseries" },
      { id: "cookies-chocolat", name: "Cookies pepites chocolat", price: 1.70, category: "viennoiseries" },
      { id: "donut-nature", name: "Donut nature", price: 1.80, category: "viennoiseries" },
      { id: "donut-chocolat", name: "Donut chocolat", price: 1.90, category: "viennoiseries" },
      { id: "chausson-pommes", name: "Chausson aux pommes", price: 2.00, category: "viennoiseries" },
      { id: "suisses-chocolat", name: "Suisses pepites chocolat", price: 2.00, category: "viennoiseries" },
      { id: "sable-pignons", name: "Sable aux pignons", price: 2.90, category: "viennoiseries" },
      { id: "muffin-chocolat", name: "Muffin chocolat", price: 2.90, category: "viennoiseries" },
      { id: "carre-citron", name: "Carre citron", price: 2.90, category: "viennoiseries" },
      { id: "carre-pommes", name: "Carre pommes", price: 2.90, category: "viennoiseries" },
      { id: "beignet-nutella", name: "Beignet Nutella", price: 2.90, category: "viennoiseries" },
      { id: "financier-nutella", name: "Financier Nutella", price: 3.00, category: "viennoiseries" },
      { id: "brioche", name: "Brioche", price: 3.00, category: "viennoiseries" },
      { id: "cheesecake", name: "Cheesecake", price: 3.20, category: "viennoiseries" },
      { id: "fondant-chocolat", name: "Fondant chocolat", price: 2.90, category: "viennoiseries" },
      { id: "tarte-fine-pommes", name: "Tarte fine pommes", price: 2.90, category: "viennoiseries" },
      { id: "flan-vanille", name: "Flan vanille", price: 2.90, category: "viennoiseries" },
      { id: "tarte-chocolat", name: "Tarte chocolat", price: 2.90, category: "viennoiseries" },
      { id: "tarte-chocolat-caramel", name: "Tarte chocolat caramel", price: 3.00, category: "viennoiseries" },
      { id: "financier-amandes", name: "Financier amandes", price: 2.90, category: "viennoiseries" },
      { id: "cheesecake-chocolat", name: "Cheesecake chocolat", price: 3.40, category: "viennoiseries" },
    ],
  },
  {
    id: "salades",
    name: "Salades",
    emoji: "🥗",
    products: [
      { id: "salade-lentilles", name: "Salade lentilles", price: 5.95, category: "salades" },
      { id: "salade-feves-pois", name: "Salade feves petits pois", price: 5.95, category: "salades" },
      { id: "green-salade", name: "Green salade", price: 5.95, category: "salades" },
      { id: "salade-quinoa-roquette", name: "Salade quinoa roquette", price: 5.95, category: "salades" },
      { id: "salade-nicoise", name: "Salade nicoise", price: 5.95, category: "salades" },
      { id: "salade-italienne", name: "Salade italienne", price: 5.95, category: "salades" },
      { id: "salade-cesar", name: "Salade Cesar", price: 6.10, category: "salades" },
      { id: "salade-pescador", name: "Salade Pescador", price: 6.10, category: "salades" },
      { id: "salade-oeuf-mollet", name: "Salade oeuf mollet", price: 6.10, category: "salades" },
      { id: "salade-tomates-mozza", name: "Salade tomates mozzarella", price: 6.10, category: "salades" },
      { id: "salade-thai", name: "Salade Thai", price: 6.10, category: "salades" },
      { id: "salade-tibetaine", name: "Salade Tibetaine", price: 6.10, category: "salades" },
      { id: "salade-pestou", name: "Salade Pestou", price: 5.95, category: "salades" },
      { id: "salade-croquante", name: "Salade croquante", price: 5.95, category: "salades" },
      { id: "salade-parme", name: "Salade de Parme", price: 6.10, category: "salades" },
      { id: "salade-parisienne", name: "Salade Parisienne", price: 6.10, category: "salades" },
      { id: "salade-saumon", name: "Salade Saumon", price: 6.10, category: "salades" },
      { id: "salade-picotin", name: "Salade Picotin", price: 6.10, category: "salades" },
    ],
  },
  {
    id: "sandwichs",
    name: "Sandwichs & Wraps",
    emoji: "🥙",
    products: [
      { id: "mini-catalan", name: "Mini sandwich Catalan", price: 3.70, category: "sandwichs" },
      { id: "mini-corse", name: "Mini sandwich Corse", price: 3.70, category: "sandwichs" },
      { id: "mini-indien", name: "Mini sandwich Indien", price: 3.70, category: "sandwichs" },
      { id: "classique-jambon", name: "Classique jambon fromage", price: 3.95, category: "sandwichs" },
      { id: "classique-poulet", name: "Classique crudites poulet", price: 4.70, category: "sandwichs" },
      { id: "classique-thon", name: "Classique crudites thon", price: 4.80, category: "sandwichs" },
      { id: "le-campagnard", name: "Le Campagnard", price: 5.10, category: "sandwichs" },
      { id: "le-vegetarien", name: "Le Vegetarien", price: 5.10, category: "sandwichs" },
      { id: "le-mexicain", name: "Le Mexicain", price: 5.10, category: "sandwichs" },
      { id: "le-gersois", name: "Le Gersois", price: 5.10, category: "sandwichs" },
      { id: "le-savoyard", name: "Le Savoyard", price: 5.10, category: "sandwichs" },
      { id: "le-vegan", name: "Le Vegan", price: 5.10, category: "sandwichs" },
      { id: "le-pan-tomate", name: "Le Pan con tomate", price: 5.10, category: "sandwichs" },
      { id: "le-corse", name: "Le Corse", price: 5.10, category: "sandwichs" },
      { id: "l-italien", name: "L'Italien", price: 5.10, category: "sandwichs" },
      { id: "le-basque", name: "Le Basque", price: 5.10, category: "sandwichs" },
      { id: "le-jabugo", name: "Le Jabugo Manchego", price: 5.10, category: "sandwichs" },
      { id: "le-catalan", name: "Le Catalan", price: 5.10, category: "sandwichs" },
      { id: "bagel-saumon", name: "Le Bagel Saumon", price: 5.10, category: "sandwichs" },
      { id: "le-norvegien", name: "Le Norvegien", price: 5.10, category: "sandwichs" },
      { id: "le-grec", name: "Le Grec", price: 5.10, category: "sandwichs" },
      { id: "le-croquant", name: "Le Croquant", price: 5.00, category: "sandwichs" },
      { id: "wrap-poulet", name: "Wrap poulet", price: 5.10, category: "sandwichs" },
      { id: "wrap-saumon", name: "Wrap saumon", price: 5.10, category: "sandwichs" },
      { id: "wrap-thon", name: "Wrap thon", price: 5.10, category: "sandwichs" },
      { id: "toaste-napoli", name: "Toaste Napoli", price: 5.10, category: "sandwichs" },
      { id: "toaste-indien", name: "Toaste Indien", price: 5.10, category: "sandwichs" },
      { id: "toaste-3-fromages", name: "Toaste 3 fromages", price: 5.10, category: "sandwichs" },
      { id: "croissant-jambon", name: "Croissant au jambon", price: 3.80, category: "sandwichs" },
    ],
  },
  {
    id: "chaud",
    name: "Chaud",
    emoji: "🫕",
    products: [
      { id: "quiche-lardons", name: "Quiche aux lardons", price: 3.80, category: "chaud" },
      { id: "quiche-legumes-chevre", name: "Quiche legumes chevre", price: 3.80, category: "chaud" },
      { id: "pizza-poulet", name: "Pizza poulet chevre tomates", price: 3.80, category: "chaud" },
      { id: "croq-morning", name: "Le Croq Morning", price: 3.80, category: "chaud" },
      { id: "friand-saucisse", name: "Friand saucisse", price: 3.80, category: "chaud" },
      { id: "tarte-salee-jour", name: "Tarte salee du jour", price: 4.80, category: "chaud" },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    emoji: "🍮",
    products: [
      { id: "duo-chocolat", name: "Duo chocolat", price: 3.10, category: "desserts" },
      { id: "tiramisu-cafe", name: "Tiramisu cafe", price: 3.10, category: "desserts" },
      { id: "tiramisu-nutella", name: "Tiramisu Nutella", price: 3.10, category: "desserts" },
      { id: "banoffee", name: "Banoffee", price: 3.10, category: "desserts" },
      { id: "passion", name: "Passion", price: 3.10, category: "desserts" },
      { id: "amandine", name: "Amandine", price: 3.10, category: "desserts" },
      { id: "tartelette-citron", name: "Tartelette citron meringuee", price: 3.10, category: "desserts" },
      { id: "tartelette-fruits", name: "Tartelette aux fruits", price: 3.10, category: "desserts" },
      { id: "l-arlequin", name: "L'Arlequin", price: 3.10, category: "desserts" },
      { id: "riz-lait", name: "Riz au lait", price: 3.10, category: "desserts" },
      { id: "chocolat-liegeois", name: "Chocolat liegeois", price: 3.10, category: "desserts" },
      { id: "twix", name: "Twix", price: 3.10, category: "desserts" },
      { id: "perle-japon", name: "Perle du Japon", price: 3.10, category: "desserts" },
      { id: "triffle-fraises", name: "Triffle aux fraises", price: 3.10, category: "desserts" },
      { id: "crumble-fruits", name: "Crumble aux fruits", price: 3.10, category: "desserts" },
      { id: "tropique-mangue", name: "Tropique mangue", price: 3.10, category: "desserts" },
      { id: "fromage-blanc", name: "Fromage blanc", price: 3.10, category: "desserts" },
      { id: "salade-fruits", name: "Salade fruits frais", price: 3.10, category: "desserts" },
      { id: "panna-cotta-framboise", name: "Panna cotta framboise", price: 3.10, category: "desserts" },
    ],
  },
]

export const allProducts = categories.flatMap((c) => c.products)
