CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  price int8 NOT NULL,
  category text NOT NULL CHECK (category IN ('viennoiseries', 'salades', 'sandwichs', 'chaud', 'desserts')),
  available boolean NOT NULL DEFAULT true,
  display_order int4 DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_first_name text NOT NULL,
  customer_last_name text NOT NULL,
  customer_email text,
  customer_phone text,
  items jsonb NOT NULL,
  total_cents int8 NOT NULL,
  pickup_time text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'ready', 'picked_up')),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS daily_specials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid REFERENCES products(id),
  date date NOT NULL,
  visible_from time DEFAULT '10:00',
  created_at timestamptz DEFAULT now(),
  UNIQUE(date)
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_specials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "products_public_read" ON products FOR SELECT USING (true);
CREATE POLICY "products_service_write" ON products FOR ALL USING (true);
CREATE POLICY "orders_insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "orders_read" ON orders FOR SELECT USING (true);
CREATE POLICY "orders_update" ON orders FOR UPDATE USING (true);
CREATE POLICY "daily_specials_read" ON daily_specials FOR SELECT USING (true);
CREATE POLICY "daily_specials_write" ON daily_specials FOR ALL USING (true);

INSERT INTO products (name, price, category, display_order) VALUES
('Croissant au beurre', 110, 'viennoiseries', 1),
('Pain au chocolat', 120, 'viennoiseries', 2),
('Pain au lait', 120, 'viennoiseries', 3),
('Brioche à tête', 120, 'viennoiseries', 4),
('Pain aux raisins', 140, 'viennoiseries', 5),
('Cookies pépites de chocolat', 170, 'viennoiseries', 6),
('Donut nature', 180, 'viennoiseries', 7),
('Donut chocolat', 190, 'viennoiseries', 8),
('Chausson aux pommes', 200, 'viennoiseries', 9),
('Suisses pépites de chocolat', 200, 'viennoiseries', 10),
('Sablé aux pignons', 290, 'viennoiseries', 11),
('Muffin chocolat', 290, 'viennoiseries', 12),
('Carré citron', 290, 'viennoiseries', 13),
('Carré pommes', 290, 'viennoiseries', 14),
('Beignet Nutella', 290, 'viennoiseries', 15),
('Financier Nutella', 300, 'viennoiseries', 16),
('Brioche', 300, 'viennoiseries', 17),
('Cheesecake', 320, 'viennoiseries', 18),
('Fondant au chocolat', 290, 'viennoiseries', 19),
('Tarte fine aux pommes', 290, 'viennoiseries', 20),
('Flan vanille', 290, 'viennoiseries', 21),
('Tarte chocolat', 290, 'viennoiseries', 22),
('Tarte chocolat caramel', 300, 'viennoiseries', 23),
('Financier amandes blanches', 290, 'viennoiseries', 24),
('Cheesecake chocolat', 340, 'viennoiseries', 25),
('Salade lentilles', 595, 'salades', 1),
('Salade fèves et petits pois', 595, 'salades', 2),
('Green salade', 595, 'salades', 3),
('Salade quinoa roquette', 595, 'salades', 4),
('Salade niçoise', 595, 'salades', 5),
('Salade italienne', 595, 'salades', 6),
('Salade César', 610, 'salades', 7),
('Salade Pescador', 610, 'salades', 8),
('Salade œuf mollet', 610, 'salades', 9),
('Salade tomates mozzarella', 610, 'salades', 10),
('Salade Thaï', 610, 'salades', 11),
('Salade Tibétaine', 610, 'salades', 12),
('Salade Pestou', 595, 'salades', 13),
('Salade croquante', 595, 'salades', 14),
('Salade de Parme', 610, 'salades', 15),
('Salade Parisienne', 610, 'salades', 16),
('Salade Saumon', 610, 'salades', 17),
('Salade Picotin', 610, 'salades', 18),
('Mini sandwich Catalan', 370, 'sandwichs', 1),
('Mini sandwich Corse', 370, 'sandwichs', 2),
('Mini sandwich Indien', 370, 'sandwichs', 3),
('Classique jambon fromage', 395, 'sandwichs', 4),
('Classique crudités poulet', 470, 'sandwichs', 5),
('Classique crudités thon', 480, 'sandwichs', 6),
('Le Campagnard', 510, 'sandwichs', 7),
('Le Végétarien', 510, 'sandwichs', 8),
('Le Mexicain', 510, 'sandwichs', 9),
('Le Gersois', 510, 'sandwichs', 10),
('Le Savoyard', 510, 'sandwichs', 11),
('Le Végan', 510, 'sandwichs', 12),
('Le Pan con tomate', 510, 'sandwichs', 13),
('Le Corse', 510, 'sandwichs', 14),
('L''Italien', 510, 'sandwichs', 15),
('Le Basque', 510, 'sandwichs', 16),
('Le Jabugo Manchego', 510, 'sandwichs', 17),
('Le Catalan', 510, 'sandwichs', 18),
('Le Bagel Saumon', 510, 'sandwichs', 19),
('Le Norvégien', 510, 'sandwichs', 20),
('Le Grec', 510, 'sandwichs', 21),
('Le Croquant', 500, 'sandwichs', 22),
('Wrap poulet', 510, 'sandwichs', 23),
('Wrap saumon', 510, 'sandwichs', 24),
('Wrap thon', 510, 'sandwichs', 25),
('Toaste Napoli', 510, 'sandwichs', 26),
('Toaste Indien', 510, 'sandwichs', 27),
('Toaste 3 fromages', 510, 'sandwichs', 28),
('Croissant au jambon', 380, 'sandwichs', 29),
('Quiche aux lardons', 380, 'chaud', 1),
('Quiche légumes chèvre', 380, 'chaud', 2),
('Pizza poulet chèvre tomates', 380, 'chaud', 3),
('Le Croq Morning', 380, 'chaud', 4),
('Friand saucisse', 380, 'chaud', 5),
('Tarte salée du jour', 480, 'chaud', 6),
('Duo chocolat', 310, 'desserts', 1),
('Tiramisu café', 310, 'desserts', 2),
('Tiramisu Nutella', 310, 'desserts', 3),
('Banoffee', 310, 'desserts', 4),
('Passion', 310, 'desserts', 5),
('Amandine', 310, 'desserts', 6),
('Tartelette citron meringuée', 310, 'desserts', 7),
('Tartelette aux fruits', 310, 'desserts', 8),
('L''Arlequin', 310, 'desserts', 9),
('Riz au lait', 310, 'desserts', 10),
('Chocolat liégeois', 310, 'desserts', 11),
('Twix', 310, 'desserts', 12),
('Perle du Japon', 310, 'desserts', 13),
('Triffle aux fraises', 310, 'desserts', 14),
('Crumble aux fruits', 310, 'desserts', 15),
('Tropique mangue', 310, 'desserts', 16),
('Fromage blanc', 310, 'desserts', 17),
('Salade fruits frais', 310, 'desserts', 18),
('Panna cotta framboise', 310, 'desserts', 19);
